version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: resume-advisor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - resume-advisor-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resume_advisor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # - mysql_data:/var/lib/mysql # For production
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - resume-advisor-network

  api:
    build: ./api-service
    container_name: flask-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - resume-advisor-network
    volumes:
      - ./api-service:/app

volumes:
  mysql_data:


networks:
  resume-advisor-network:
    driver: bridge
