version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resume_advisor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - resume-advisor-network

  api:
    build: ./api-service
    container_name: flask-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:8080" # 把 host 的 80 映射到 container 的 8080
    env_file:
      - ./.env
    networks:
      - resume-advisor-network
    volumes:
      - ./api-service:/app

networks:
  resume-advisor-network:
    driver: bridge
