version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resume_advisor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # - mysql_data:/var/lib/mysql # For production
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - resume-advisor-network

  api:
    build: ./api-service
    container_name: flask-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:8080"
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: user
    #   MYSQL_PASSWORD: password
    #   MYSQL_DB: resume_advisor
    env_file:
      - ./.env
    networks:
      - resume-advisor-network

volumes:
  mysql_data:


networks:
  resume-advisor-network:
    driver: bridge
